### ISSUE TITLE
Wardriving Accuracy

### ISSUE THREAD

**Issue by JD-2006** [cyberartemio/wardriver-pwnagotchi-plugin#1]
I saw you had a comment in your code about calculating accuracy. I noticed for the webgpsmap plugin they used 50 meters for the AP location. That's prob a good guess considering we're using tiny Pi antenna and we're only getting signals that happen to come through walls/windows etc.

But I think Wigle uses GPS accuracy as a variable. I have searched for more info on how they calculate that to no avail.

As a nerdy rabbithole I found this formulae: https://blog.oplopanax.ca/2012/11/calculating-gps-accuracy/

I might try a python script to calculate from some GPS logging. My Pi does not use gpsd but many others do and I'm not sure how that differece wouls matter.

**Comment by cyberartemio** [comment]
While I was looking for information about GPS accuracy, I also saw this article though I didn't go deep because it was late at night lol. Thank you for the information and if you can figure out how to calculate the accuracy feel free to send a PR. 

Let me know if you write that script so I can also test it. In the last couple of days I've actually wardrived with my pwnagotchi and my Android with WiGLE app so I have some data to compare. I didn't compare the data yet but I'm gonna be doing in the next days.

In the meantime I'm gonna change the accuracy to 50 meters.

**Comment by JD-2006** [comment]
As an aside I use Locus Pro for android for mapping and creating GPS tracks, POI's etc. Online/Offline maps, import/export of data too.

**Comment by cyberartemio** [comment]
I'm closing this since it's been stale for a while. Gonna reopen it when there is any update. For the moment, I'm gonna keep static value `50` for the accuracy in meters.
